import { PresetType } from './types'

export const standard: PresetType = {
  id: 1,
  name: 'Standard',
  description: 'Has everything you need to start playing.',
  data: {
    categories: [
      { id: 1, name: 'Animals' },
      { id: 2, name: 'Food' },
      { id: 3, name: 'Colors' },
      { id: 4, name: 'Shapes' },
      { id: 5, name: 'Human states' },
      { id: 6, name: 'Clothes' },
      { id: 7, name: 'Body parts' },
      { id: 8, name: 'Furniture' },
      { id: 9, name: 'Kitchen' },
      { id: 10, name: 'Sports' },
      { id: 11, name: 'Transport' },
      { id: 12, name: 'Jobs' },
      { id: 13, name: 'Hobbies' },
      { id: 14, name: 'Nature' },
      { id: 15, name: 'Weather' },
      { id: 16, name: 'People (famous)' },
      { id: 17, name: 'People (family)' },
      { id: 18, name: 'Characters (famous)' },
      { id: 19, name: 'Characters (stereotypes)' },
      { id: 20, name: 'Car brands' },
      { id: 21, name: 'Countries' },
      { id: 22, name: 'Cities' },
      { id: 23, name: 'Places' }
    ],
    words: [
      // 24 words of Animals category
      { id: 1, text: 'cat', categoryId: 1 },
      { id: 2, text: 'dog', categoryId: 1 },
      { id: 3, text: 'bird', categoryId: 1 },
      { id: 4, text: 'fish', categoryId: 1 },
      { id: 5, text: 'horse', categoryId: 1 },
      { id: 6, text: 'cow', categoryId: 1 },
      { id: 7, text: 'pig', categoryId: 1 },
      { id: 8, text: 'sheep', categoryId: 1 },
      { id: 9, text: 'mouse', categoryId: 1 },
      { id: 10, text: 'rabbit', categoryId: 1 },
      { id: 11, text: 'duck', categoryId: 1 },
      { id: 12, text: 'goat', categoryId: 1 },
      { id: 13, text: 'chicken', categoryId: 1 },
      { id: 14, text: 'elephant', categoryId: 1 },
      { id: 15, text: 'lion', categoryId: 1 },
      { id: 16, text: 'tiger', categoryId: 1 },
      { id: 17, text: 'bear', categoryId: 1 },
      { id: 18, text: 'monkey', categoryId: 1 },
      { id: 19, text: 'snake', categoryId: 1 },
      { id: 20, text: 'frog', categoryId: 1 },
      { id: 21, text: 'dolphin', categoryId: 1 },
      { id: 22, text: 'whale', categoryId: 1 },
      { id: 23, text: 'shark', categoryId: 1 },
      { id: 24, text: 'penguin', categoryId: 1 },
      // 24 words of Food category
      { id: 25, text: 'apple', categoryId: 2 },
      { id: 26, text: 'banana', categoryId: 2 },
      { id: 27, text: 'orange', categoryId: 2 },
      { id: 28, text: 'pear', categoryId: 2 },
      { id: 29, text: 'grape', categoryId: 2 },
      { id: 30, text: 'strawberry', categoryId: 2 },
      { id: 31, text: 'watermelon', categoryId: 2 },
      { id: 32, text: 'melon', categoryId: 2 },
      { id: 33, text: 'pineapple', categoryId: 2 },
      { id: 34, text: 'lemon', categoryId: 2 },
      { id: 35, text: 'peach', categoryId: 2 },
      { id: 36, text: 'plum', categoryId: 2 },
      { id: 37, text: 'cherry', categoryId: 2 },
      { id: 38, text: 'coconut', categoryId: 2 },
      { id: 39, text: 'avocado', categoryId: 2 },
      { id: 40, text: 'mango', categoryId: 2 },
      { id: 41, text: 'kiwi', categoryId: 2 },
      { id: 42, text: 'tomato', categoryId: 2 },
      { id: 43, text: 'potato', categoryId: 2 },
      { id: 44, text: 'carrot', categoryId: 2 },
      { id: 45, text: 'onion', categoryId: 2 },
      { id: 46, text: 'cucumber', categoryId: 2 },
      { id: 47, text: 'pepper', categoryId: 2 },
      { id: 48, text: 'garlic', categoryId: 2 },
      // 24 words of Colors category
      { id: 49, text: 'red', categoryId: 3 },
      { id: 50, text: 'orange', categoryId: 3 },
      { id: 51, text: 'yellow', categoryId: 3 },
      { id: 52, text: 'green', categoryId: 3 },
      { id: 53, text: 'blue', categoryId: 3 },
      { id: 54, text: 'purple', categoryId: 3 },
      { id: 55, text: 'pink', categoryId: 3 },
      { id: 56, text: 'brown', categoryId: 3 },
      { id: 57, text: 'black', categoryId: 3 },
      { id: 58, text: 'white', categoryId: 3 },
      { id: 59, text: 'grey', categoryId: 3 },
      { id: 60, text: 'gold', categoryId: 3 },
      { id: 61, text: 'silver', categoryId: 3 },
      { id: 62, text: 'violet', categoryId: 3 },
      { id: 63, text: 'indigo', categoryId: 3 },
      { id: 64, text: 'turquoise', categoryId: 3 },
      { id: 65, text: 'maroon', categoryId: 3 },
      { id: 66, text: 'crimson', categoryId: 3 },
      { id: 67, text: 'lavender', categoryId: 3 },
      { id: 68, text: 'magenta', categoryId: 3 },
      { id: 69, text: 'amber', categoryId: 3 },
      { id: 70, text: 'beige', categoryId: 3 },
      { id: 71, text: 'coral', categoryId: 3 },
      { id: 72, text: 'emerald', categoryId: 3 },
      // 14 words of Shapes category
      { id: 73, text: 'circle', categoryId: 4 },
      { id: 74, text: 'square', categoryId: 4 },
      { id: 75, text: 'triangle', categoryId: 4 },
      { id: 76, text: 'rectangle', categoryId: 4 },
      { id: 77, text: 'oval', categoryId: 4 },
      { id: 78, text: 'star', categoryId: 4 },
      { id: 79, text: 'heart', categoryId: 4 },
      { id: 80, text: 'diamond', categoryId: 4 },
      { id: 81, text: 'hexagon', categoryId: 4 },
      { id: 82, text: 'pentagon', categoryId: 4 },
      { id: 83, text: 'rhombus', categoryId: 4 },
      { id: 84, text: 'trapezoid', categoryId: 4 },
      { id: 85, text: 'cube', categoryId: 4 },
      { id: 86, text: 'sphere', categoryId: 4 },
      // words of Human states category
      {
        id: 87,
        text: 'happy',
        categoryId: 5,
        relatedWords: [{ id: 1, wordId: 86 }]
      },
      // words of clothes category
      { id: 88, text: 'shirt', categoryId: 6 },
      { id: 89, text: 'pants', categoryId: 6 },
      { id: 90, text: 'shoes', categoryId: 6 },
      { id: 91, text: 'socks', categoryId: 6 },
      { id: 92, text: 'hat', categoryId: 6 },
      { id: 93, text: 'glasses', categoryId: 6 },
      { id: 94, text: 'jacket', categoryId: 6 },
      { id: 95, text: 'coat', categoryId: 6 },
      { id: 96, text: 'dress', categoryId: 6 },
      { id: 97, text: 'skirt', categoryId: 6 },
      { id: 98, text: 'shorts', categoryId: 6 },
      { id: 99, text: 'tie', categoryId: 6 },
      { id: 100, text: 'scarf', categoryId: 6 },
      { id: 101, text: 'gloves', categoryId: 6 },
      { id: 102, text: 'belt', categoryId: 6 },
      { id: 103, text: 'underwear', categoryId: 6 },
      { id: 104, text: 'swimsuit', categoryId: 6 },
      { id: 105, text: 'sweater', categoryId: 6 },
      { id: 106, text: 'sweatshirt', categoryId: 6 },
      { id: 107, text: 'jeans', categoryId: 6 },
      { id: 108, text: 'slippers', categoryId: 6 },
      { id: 109, text: 'boots', categoryId: 6 },
      { id: 110, text: 'sandals', categoryId: 6 },
      { id: 111, text: 'flip-flops', categoryId: 6 },
      { id: 112, text: 'hoodie', categoryId: 6 },
      { id: 113, text: 'raincoat', categoryId: 6 },
      // words of Body parts category
      { id: 114, text: 'head', categoryId: 7 },
      { id: 115, text: 'face', categoryId: 7 },
      { id: 116, text: 'eye', categoryId: 7 },
      { id: 117, text: 'nose', categoryId: 7 },
      { id: 118, text: 'ear', categoryId: 7 },
      { id: 119, text: 'mouth', categoryId: 7 },
      { id: 120, text: 'tongue', categoryId: 7 },
      { id: 121, text: 'tooth', categoryId: 7 },
      { id: 122, text: 'hair', categoryId: 7 },
      { id: 123, text: 'neck', categoryId: 7 },
      { id: 124, text: 'shoulder', categoryId: 7 },
      { id: 125, text: 'arm', categoryId: 7 },
      { id: 126, text: 'hand', categoryId: 7 },
      { id: 127, text: 'finger', categoryId: 7 },
      { id: 128, text: 'chest', categoryId: 7 },
      { id: 129, text: 'stomach', categoryId: 7 },
      { id: 130, text: 'back', categoryId: 7 },
      { id: 131, text: 'waist', categoryId: 7 },
      { id: 132, text: 'hip', categoryId: 7 },
      { id: 133, text: 'leg', categoryId: 7 },
      { id: 134, text: 'foot', categoryId: 7 },
      { id: 135, text: 'toe', categoryId: 7 },
      { id: 136, text: 'knee', categoryId: 7 },
      { id: 137, text: 'ankle', categoryId: 7 },
      { id: 138, text: 'elbow', categoryId: 7 },
      { id: 139, text: 'wrist', categoryId: 7 },
      { id: 140, text: 'chin', categoryId: 7 },
      { id: 141, text: 'forehead', categoryId: 7 },
      { id: 142, text: 'cheek', categoryId: 7 },
      // 15 words of Furniture category
      { id: 143, text: 'chair', categoryId: 8 },
      { id: 144, text: 'table', categoryId: 8 },
      { id: 145, text: 'bed', categoryId: 8 },
      { id: 146, text: 'sofa', categoryId: 8 },
      { id: 147, text: 'couch', categoryId: 8 },
      { id: 148, text: 'armchair', categoryId: 8 },
      { id: 149, text: 'stool', categoryId: 8 },
      { id: 150, text: 'bench', categoryId: 8 },
      { id: 151, text: 'desk', categoryId: 8 },
      { id: 152, text: 'dresser', categoryId: 8 },
      { id: 153, text: 'wardrobe', categoryId: 8 },
      { id: 154, text: 'bookcase', categoryId: 8 },
      { id: 155, text: 'shelf', categoryId: 8 },
      { id: 156, text: 'cabinet', categoryId: 8 },
      { id: 157, text: 'cupboard', categoryId: 8 },
      // 15 words of Kitchen category
      { id: 158, text: 'kitchen', categoryId: 9 },
      { id: 159, text: 'oven', categoryId: 9 },
      { id: 160, text: 'fridge', categoryId: 9 },
      { id: 161, text: 'freezer', categoryId: 9 },
      { id: 162, text: 'microwave', categoryId: 9 },
      { id: 163, text: 'dishwasher', categoryId: 9 },
      { id: 164, text: 'sink', categoryId: 9 },
      { id: 165, text: 'stove', categoryId: 9 },
      { id: 166, text: 'toaster', categoryId: 9 },
      { id: 167, text: 'blender', categoryId: 9 },
      { id: 168, text: 'kettle', categoryId: 9 },
      { id: 169, text: 'pot', categoryId: 9 },
      { id: 170, text: 'pan', categoryId: 9 },
      { id: 171, text: 'knife', categoryId: 9 },
      { id: 172, text: 'fork', categoryId: 9 },
      { id: 173, text: 'spoon', categoryId: 9 },
      { id: 174, text: 'plate', categoryId: 9 },
      { id: 175, text: 'bowl', categoryId: 9 },
      { id: 176, text: 'glass', categoryId: 9 },
      // 15 words of Sports category
      { id: 177, text: 'football', categoryId: 10 },
      { id: 178, text: 'basketball', categoryId: 10 },
      { id: 179, text: 'tennis', categoryId: 10 },
      { id: 180, text: 'volleyball', categoryId: 10 },
      { id: 181, text: 'rugby', categoryId: 10 },
      { id: 182, text: 'golf', categoryId: 10 },
      { id: 183, text: 'hockey', categoryId: 10 },
      { id: 184, text: 'baseball', categoryId: 10 },
      { id: 185, text: 'cricket', categoryId: 10 },
      { id: 186, text: 'swimming', categoryId: 10 },
      { id: 187, text: 'boxing', categoryId: 10 },
      { id: 188, text: 'skiing', categoryId: 10 },
      { id: 189, text: 'snowboarding', categoryId: 10 },
      { id: 190, text: 'cycling', categoryId: 10 },
      { id: 191, text: 'running', categoryId: 10 },
      // 15 words of Transport category
      { id: 192, text: 'car', categoryId: 11 },
      { id: 193, text: 'bus', categoryId: 11 },
      { id: 194, text: 'train', categoryId: 11 },
      { id: 195, text: 'plane', categoryId: 11 },
      { id: 196, text: 'ship', categoryId: 11 },
      { id: 197, text: 'bike', categoryId: 11 },
      { id: 198, text: 'motorbike', categoryId: 11 },
      { id: 199, text: 'scooter', categoryId: 11 },
      { id: 200, text: 'truck', categoryId: 11 },
      { id: 201, text: 'van', categoryId: 11 },
      { id: 202, text: 'taxi', categoryId: 11 },
      { id: 203, text: 'tram', categoryId: 11 },
      { id: 204, text: 'subway', categoryId: 11 },
      { id: 205, text: 'helicopter', categoryId: 11 },
      { id: 206, text: 'rocket', categoryId: 11 },
      // 15 words of Jobs category
      { id: 207, text: 'doctor', categoryId: 12 },
      { id: 208, text: 'nurse', categoryId: 12 },
      { id: 209, text: 'teacher', categoryId: 12 },
      { id: 210, text: 'policeman', categoryId: 12 },
      { id: 211, text: 'fireman', categoryId: 12 },
      { id: 212, text: 'pilot', categoryId: 12 },
      { id: 213, text: 'chef', categoryId: 12 },
      { id: 214, text: 'engineer', categoryId: 12 },
      { id: 215, text: 'programmer', categoryId: 12 },
      { id: 216, text: 'lawyer', categoryId: 12 },
      { id: 217, text: 'artist', categoryId: 12 },
      { id: 218, text: 'musician', categoryId: 12 },
      { id: 219, text: 'actor', categoryId: 12 },
      { id: 220, text: 'singer', categoryId: 12 },
      { id: 221, text: 'dancer', categoryId: 12 },
      // 15 words of Hobbies category
      { id: 222, text: 'reading', categoryId: 13 },
      { id: 223, text: 'writing', categoryId: 13 },
      { id: 224, text: 'drawing', categoryId: 13 },
      { id: 225, text: 'painting', categoryId: 13 },
      { id: 226, text: 'photography', categoryId: 13 },
      { id: 227, text: 'gardening', categoryId: 13 },
      { id: 228, text: 'cooking', categoryId: 13 },
      { id: 229, text: 'swimming', categoryId: 13 },
      { id: 230, text: 'skiing', categoryId: 13 },
      { id: 231, text: 'snowboarding', categoryId: 13 },
      { id: 232, text: 'cycling', categoryId: 13 },
      { id: 233, text: 'running', categoryId: 13 },
      { id: 234, text: 'hiking', categoryId: 13 },
      { id: 235, text: 'fishing', categoryId: 13 },
      { id: 236, text: 'singing', categoryId: 13 },
      // 15 words of Nature category
      { id: 237, text: 'sun', categoryId: 14 },
      { id: 238, text: 'moon', categoryId: 14 },
      { id: 239, text: 'star', categoryId: 14 },
      { id: 240, text: 'cloud', categoryId: 14 },
      { id: 241, text: 'rain', categoryId: 14 },
      { id: 242, text: 'snow', categoryId: 14 },
      { id: 243, text: 'wind', categoryId: 14 },
      { id: 244, text: 'thunder', categoryId: 14 },
      { id: 245, text: 'lightning', categoryId: 14 },
      { id: 246, text: 'fog', categoryId: 14 },
      { id: 247, text: 'forest', categoryId: 14 },
      { id: 248, text: 'mountain', categoryId: 14 },
      { id: 249, text: 'river', categoryId: 14 },
      { id: 250, text: 'ocean', categoryId: 14 },
      { id: 251, text: 'sea', categoryId: 14 },
      // 15 words of Weather category
      { id: 252, text: 'spring', categoryId: 15 },
      { id: 253, text: 'summer', categoryId: 15 },
      { id: 254, text: 'autumn', categoryId: 15 },
      { id: 255, text: 'winter', categoryId: 15 },
      { id: 256, text: 'day', categoryId: 15 },
      { id: 257, text: 'night', categoryId: 15 },
      { id: 258, text: 'morning', categoryId: 15 },
      { id: 259, text: 'afternoon', categoryId: 15 },
      { id: 260, text: 'evening', categoryId: 15 },
      { id: 261, text: 'rainbow', categoryId: 15 },
      { id: 262, text: 'thunderstorm', categoryId: 15 },
      { id: 263, text: 'flood', categoryId: 15 },
      { id: 264, text: 'blizzard', categoryId: 15 },
      { id: 265, text: 'hurricane', categoryId: 15 },
      { id: 266, text: 'tornado', categoryId: 15 },
      // 15 words of People (famous) category
      { id: 267, text: 'Bill Gates', categoryId: 16 },
      { id: 268, text: 'Steve Jobs', categoryId: 16 },
      { id: 269, text: 'Elon Musk', categoryId: 16 },
      { id: 270, text: 'Mark Zuckerberg', categoryId: 16 },
      { id: 271, text: 'Jeff Bezos', categoryId: 16 },
      { id: 272, text: 'Warren Buffet', categoryId: 16 },
      { id: 273, text: 'Jack Ma', categoryId: 16 },
      { id: 274, text: 'Jack Dorsey', categoryId: 16 },
      { id: 275, text: 'Larry Page', categoryId: 16 },
      { id: 276, text: 'Sergey Brin', categoryId: 16 },
      { id: 277, text: 'Larry Ellison', categoryId: 16 },
      { id: 278, text: 'Larry Page', categoryId: 16 },
      { id: 279, text: 'Sergey Brin', categoryId: 16 },
      { id: 280, text: 'Larry Ellison', categoryId: 16 },
      { id: 281, text: 'Larry Page', categoryId: 16 },
      // 15 words of People (family) category
      { id: 1267, text: 'mother', categoryId: 17 },
      { id: 1268, text: 'father', categoryId: 17 },
      { id: 1269, text: 'brother', categoryId: 17 },
      { id: 1270, text: 'sister', categoryId: 17 },
      { id: 1271, text: 'grandmother', categoryId: 17 },
      { id: 1272, text: 'grandfather', categoryId: 17 },
      { id: 1273, text: 'uncle', categoryId: 17 },
      { id: 1274, text: 'aunt', categoryId: 17 },
      { id: 1275, text: 'cousin', categoryId: 17 },
      { id: 1276, text: 'son', categoryId: 17 },
      { id: 1277, text: 'daughter', categoryId: 17 },
      { id: 1278, text: 'husband', categoryId: 17 },
      { id: 1279, text: 'wife', categoryId: 17 },
      { id: 1280, text: 'friend', categoryId: 17 },
      { id: 1281, text: 'enemy', categoryId: 17 },
      { id: 1282, text: 'king', categoryId: 17 },
      { id: 1283, text: 'queen', categoryId: 17 },
      { id: 1284, text: 'prince', categoryId: 17 },
      { id: 1285, text: 'princess', categoryId: 17 },
      { id: 1286, text: 'knight', categoryId: 17 },
      { id: 1287, text: 'lord', categoryId: 17 },
      { id: 1288, text: 'lady', categoryId: 17 },
      { id: 1289, text: 'baron', categoryId: 17 },
      { id: 1290, text: 'baroness', categoryId: 17 },
      // 15 words of Characters (famous) category
      { id: 291, text: 'Batman', categoryId: 18 },
      { id: 292, text: 'Superman', categoryId: 18 },
      { id: 293, text: 'Spiderman', categoryId: 18 },
      { id: 294, text: 'Ironman', categoryId: 18 },
      { id: 295, text: 'Thor', categoryId: 18 },
      { id: 296, text: 'Captain America', categoryId: 18 },
      { id: 297, text: 'Hulk', categoryId: 18 },
      { id: 298, text: 'Wolverine', categoryId: 18 },
      { id: 299, text: 'Deadpool', categoryId: 18 },
      { id: 300, text: 'Hawkeye', categoryId: 18 },
      { id: 301, text: 'Black Widow', categoryId: 18 },
      { id: 302, text: 'Black Panther', categoryId: 18 },
      // 15 words of Characters (stereotypes) category
      { id: 303, text: 'gentleman', categoryId: 19 },
      { id: 304, text: 'gentlewoman', categoryId: 19 },
      { id: 305, text: 'cowboy', categoryId: 19 },
      { id: 306, text: 'cowgirl', categoryId: 19 },
      { id: 307, text: 'pirate', categoryId: 19 },
      { id: 308, text: 'princess', categoryId: 19 },
      { id: 309, text: 'prince', categoryId: 19 },
      { id: 310, text: 'knight', categoryId: 19 },
      { id: 311, text: 'wizard', categoryId: 19 },
      { id: 312, text: 'witch', categoryId: 19 },
      { id: 313, text: 'king', categoryId: 19 },
      { id: 314, text: 'queen', categoryId: 19 },
      { id: 315, text: 'baron', categoryId: 19 },
      { id: 316, text: 'baroness', categoryId: 19 },
      { id: 317, text: 'vampire', categoryId: 19 },
      { id: 318, text: 'werewolf', categoryId: 19 },
      { id: 319, text: 'zombie', categoryId: 19 },
      { id: 320, text: 'ghost', categoryId: 19 },
      { id: 321, text: 'demon', categoryId: 19 },
      { id: 322, text: 'angel', categoryId: 19 },
      { id: 323, text: 'devil', categoryId: 19 },
      { id: 324, text: 'alien', categoryId: 19 },
      { id: 325, text: 'robot', categoryId: 19 },
      { id: 326, text: 'cyborg', categoryId: 19 },
      { id: 331, text: 'nerd', categoryId: 19 },
      { id: 332, text: 'athlete', categoryId: 19 },
      // 15 words of Car brands category
      { id: 333, text: 'Audi', categoryId: 20 },
      { id: 334, text: 'BMW', categoryId: 20 },
      { id: 335, text: 'Mercedes', categoryId: 20 },
      { id: 336, text: 'Volkswagen', categoryId: 20 },
      { id: 337, text: 'Porsche', categoryId: 20 },
      { id: 338, text: 'Ferrari', categoryId: 20 },
      { id: 339, text: 'Lamborghini', categoryId: 20 },
      { id: 340, text: 'Maserati', categoryId: 20 },
      { id: 341, text: 'Aston Martin', categoryId: 20 },
      { id: 342, text: 'Bugatti', categoryId: 20 },
      { id: 343, text: 'Ford', categoryId: 20 },
      { id: 344, text: 'Chevrolet', categoryId: 20 },
      { id: 345, text: 'Dodge', categoryId: 20 },
      { id: 346, text: 'Chrysler', categoryId: 20 },
      { id: 347, text: 'Jeep', categoryId: 20 },
      { id: 348, text: 'Cadillac', categoryId: 20 },
      { id: 349, text: 'Lincoln', categoryId: 20 },
      { id: 350, text: 'Tesla', categoryId: 20 },
      { id: 351, text: 'Toyota', categoryId: 20 },
      { id: 352, text: 'Honda', categoryId: 20 },
      { id: 353, text: 'Nissan', categoryId: 20 },
      { id: 354, text: 'Mitsubishi', categoryId: 20 },
      { id: 355, text: 'Subaru', categoryId: 20 },
      { id: 356, text: 'Hyundai', categoryId: 20 },
      { id: 357, text: 'Kia', categoryId: 20 },
      { id: 358, text: 'Suzuki', categoryId: 20 },
      { id: 359, text: 'Mazda', categoryId: 20 },
      { id: 360, text: 'Volvo', categoryId: 20 },
      { id: 361, text: 'Saab', categoryId: 20 },
      { id: 362, text: 'Acura', categoryId: 20 },
      { id: 363, text: 'Lexus', categoryId: 20 },
      { id: 364, text: 'Infiniti', categoryId: 20 },
      { id: 365, text: 'Land Rover', categoryId: 20 },
      { id: 366, text: 'Jaguar', categoryId: 20 },
      { id: 367, text: 'Bentley', categoryId: 20 },
      { id: 368, text: 'Rolls-Royce', categoryId: 20 },
      { id: 369, text: 'Peugeot', categoryId: 20 },
      { id: 370, text: 'Citroen', categoryId: 20 },
      { id: 371, text: 'Renault', categoryId: 20 },
      { id: 372, text: 'Opel', categoryId: 20 },
      { id: 373, text: 'Fiat', categoryId: 20 },
      { id: 374, text: 'Alfa Romeo', categoryId: 20 },
      { id: 375, text: 'Lancia', categoryId: 20 },
      { id: 376, text: 'Dacia', categoryId: 20 },
      { id: 377, text: 'Skoda', categoryId: 20 },
      { id: 378, text: 'Seat', categoryId: 20 },
      { id: 379, text: 'Mini', categoryId: 20 },
      { id: 380, text: 'Smart', categoryId: 20 },
      { id: 381, text: 'Morgan', categoryId: 20 },
      { id: 382, text: 'McLaren', categoryId: 20 },
      // 15 words of Countries category
      { id: 383, text: 'Afghanistan', categoryId: 21 },
      { id: 384, text: 'Albania', categoryId: 21 },
      { id: 385, text: 'Algeria', categoryId: 21 },
      { id: 386, text: 'Andorra', categoryId: 21 },
      { id: 387, text: 'Angola', categoryId: 21 },
      { id: 388, text: 'Antigua and Barbuda', categoryId: 21 },
      { id: 389, text: 'Argentina', categoryId: 21 },
      { id: 390, text: 'Armenia', categoryId: 21 },
      { id: 391, text: 'Australia', categoryId: 21 },
      { id: 392, text: 'Austria', categoryId: 21 },
      { id: 393, text: 'Azerbaijan', categoryId: 21 },
      { id: 394, text: 'Bahamas', categoryId: 21 },
      { id: 395, text: 'Bahrain', categoryId: 21 },
      { id: 396, text: 'Bangladesh', categoryId: 21 },
      { id: 397, text: 'Barbados', categoryId: 21 },
      { id: 398, text: 'Belarus', categoryId: 21 },
      { id: 399, text: 'Belgium', categoryId: 21 },
      { id: 400, text: 'Belize', categoryId: 21 },
      { id: 401, text: 'Benin', categoryId: 21 },
      { id: 402, text: 'Bhutan', categoryId: 21 },
      { id: 403, text: 'Bolivia', categoryId: 21 },
      { id: 404, text: 'Bosnia and Herzegovina', categoryId: 21 },
      { id: 405, text: 'Botswana', categoryId: 21 },
      { id: 406, text: 'Brazil', categoryId: 21 },
      { id: 407, text: 'Brunei', categoryId: 21 },
      { id: 408, text: 'Bulgaria', categoryId: 21 },
      { id: 409, text: 'Burkina Faso', categoryId: 21 },
      { id: 410, text: 'Burundi', categoryId: 21 },
      { id: 411, text: 'Cambodia', categoryId: 21 },
      { id: 412, text: 'Cameroon', categoryId: 21 },
      { id: 413, text: 'Canada', categoryId: 21 },
      { id: 414, text: 'Cape Verde', categoryId: 21 },
      { id: 415, text: 'Central African Republic', categoryId: 21 },
      { id: 416, text: 'Chad', categoryId: 21 },
      { id: 417, text: 'Chile', categoryId: 21 },
      { id: 418, text: 'China', categoryId: 21 },
      { id: 419, text: 'Colombia', categoryId: 21 },
      { id: 420, text: 'Comoros', categoryId: 21 },
      { id: 421, text: 'Congo', categoryId: 21 },
      { id: 422, text: 'Costa Rica', categoryId: 21 },
      { id: 423, text: "Cote d'Ivoire", categoryId: 21 },
      { id: 424, text: 'Croatia', categoryId: 21 },
      { id: 425, text: 'Cuba', categoryId: 21 },
      { id: 426, text: 'Cyprus', categoryId: 21 },
      { id: 427, text: 'Czech Republic', categoryId: 21 },
      { id: 428, text: 'Denmark', categoryId: 21 },
      { id: 429, text: 'Djibouti', categoryId: 21 },
      { id: 430, text: 'Dominica', categoryId: 21 },
      { id: 431, text: 'Dominican Republic', categoryId: 21 },
      { id: 432, text: 'East Timor', categoryId: 21 },
      { id: 433, text: 'Ecuador', categoryId: 21 },
      { id: 434, text: 'Egypt', categoryId: 21 },
      { id: 435, text: 'El Salvador', categoryId: 21 },
      { id: 436, text: 'Equatorial Guinea', categoryId: 21 },
      { id: 437, text: 'Eritrea', categoryId: 21 },
      { id: 438, text: 'Estonia', categoryId: 21 },
      { id: 439, text: 'Ethiopia', categoryId: 21 },
      { id: 440, text: 'Fiji', categoryId: 21 },
      { id: 441, text: 'Finland', categoryId: 21 },
      { id: 442, text: 'France', categoryId: 21 },
      { id: 443, text: 'Gabon', categoryId: 21 },
      { id: 444, text: 'Gambia', categoryId: 21 },
      { id: 445, text: 'Georgia', categoryId: 21 },
      { id: 446, text: 'Germany', categoryId: 21 },
      { id: 447, text: 'Ghana', categoryId: 21 },
      { id: 448, text: 'Greece', categoryId: 21 },
      { id: 449, text: 'Grenada', categoryId: 21 },
      { id: 450, text: 'Guatemala', categoryId: 21 },
      { id: 451, text: 'Guinea', categoryId: 21 },
      { id: 452, text: 'Guinea-Bissau', categoryId: 21 },
      { id: 453, text: 'Guyana', categoryId: 21 },
      { id: 454, text: 'Haiti', categoryId: 21 },
      { id: 455, text: 'Honduras', categoryId: 21 },
      { id: 456, text: 'Hungary', categoryId: 21 },
      { id: 457, text: 'Iceland', categoryId: 21 },
      { id: 458, text: 'India', categoryId: 21 },
      { id: 459, text: 'Indonesia', categoryId: 21 },
      { id: 460, text: 'Iran', categoryId: 21 },
      { id: 461, text: 'Iraq', categoryId: 21 },
      { id: 462, text: 'Ireland', categoryId: 21 },
      // 15 words of Cities category
      { id: 463, text: 'New York', categoryId: 22 },
      { id: 464, text: 'Los Angeles', categoryId: 22 },
      { id: 465, text: 'Chicago', categoryId: 22 },
      { id: 466, text: 'Houston', categoryId: 22 },
      { id: 467, text: 'Philadelphia', categoryId: 22 },
      { id: 468, text: 'Phoenix', categoryId: 22 },
      { id: 469, text: 'San Antonio', categoryId: 22 },
      { id: 470, text: 'San Diego', categoryId: 22 },
      { id: 471, text: 'Dallas', categoryId: 22 },
      { id: 472, text: 'San Jose', categoryId: 22 },
      { id: 473, text: 'Austin', categoryId: 22 },
      { id: 474, text: 'Jacksonville', categoryId: 22 },
      { id: 475, text: 'San Francisco', categoryId: 22 },
      { id: 476, text: 'Indianapolis', categoryId: 22 },
      { id: 477, text: 'Columbus', categoryId: 22 },
      // 15 words of Places category
      { id: 478, text: 'Mount Everest', categoryId: 23 },
      { id: 479, text: 'museum', categoryId: 23 },
      { id: 480, text: 'beach', categoryId: 23 },
      { id: 481, text: 'restaurant', categoryId: 23 },
      { id: 482, text: 'zoo', categoryId: 23 },
      { id: 483, text: 'library', categoryId: 23 },
      { id: 484, text: 'park', categoryId: 23 },
      { id: 485, text: 'theater', categoryId: 23 },
      { id: 486, text: 'stadium', categoryId: 23 },
      { id: 487, text: 'castle', categoryId: 23 },
      { id: 488, text: 'cathedral', categoryId: 23 },
      { id: 489, text: 'temple', categoryId: 23 },
      { id: 490, text: 'church', categoryId: 23 },
      { id: 491, text: 'grocery store', categoryId: 23 },
      { id: 492, text: 'mall', categoryId: 23 }
    ]
  }
}
